[package]
name = "roxlap-sdl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "SDL2-hosted demo binary for the roxlap engine."

[[bin]]
name = "roxlap-sdl"
path = "src/main.rs"

[dependencies]
# Real SDL2 dep added in stage R3.
# sdl2 = "0.36"

[lints]
workspace = true
